# Generated by Django 5.1.5 on 2025-02-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
