# Generated by Django 5.1.5 on 2025-02-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapi', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
